### ISSUE TITLE
Problems getting started with LFE on Mac OSX

### ISSUE THREAD

**Issue by verdammelt** [exercism/xlfe#2] opened 2015-07-29 23:39 UTC
Following the directions found in http://help.exercism.io/getting-started-with-lfe.html I am not seeing the `rebar get-deps` and `rebar compile` steps having any affect. The document implies that a deps directory should be created (given that we find the value for ERL_LIBS from that).

There is no advice on where to run those commands from. I have tried from the following locations:

* home directory
* exercism exercises lfe directory
* exercism exercises lfe/leap directory
* home brew Cellar directory which is where lfe is installed to.

Am I running it from an invalid location or has some other part of my install gone wrong? 

NOTE: I did `brew install lfe` before seeing that the instructions said to follow the Erlang instructions first, however `brew install lfe` did in fact install erlang.

Homebrew installed lfe version 0.9.2 and erlang 17.5.

**Comment by yurrriq** [comment] 2015-07-30 00:45
Thanks for the feedback! Sorry you're having trouble..

Do you have a `rebar.config` file in your `/path/to/exercism/lfe` directory? I'm not intimately familiar with the way Exercism works so it may not be giving it to you, but you'll need a `rebar.config` there that looks like this:

```erlang
{erl_opts, [debug_info]}.
{lfe_first_files, []}.
{deps_dir, ["deps"]}.
{deps, [
    {lfe, ".*", {git, "git://github.com/rvirding/lfe.git", {tag, "0.9.2"}}},
    {ltest, ".*", {git, "git://github.com/lfex/ltest.git", "master"}}
  ]}.
```

The most important part being the [ltest][1] line. With that, after calling `rebar get-deps`, `rebar compile`, and exporting `ERL_LIBS` with the appropriate value, you should be up and running. It seems like we'll need to update the "Getting Started" guide.

=====

Just to make sure everything installed correctly, could you run the following and post the output?

```fish
lfe -noshell \
    -eval "(lfe_io:format \"~s\n\" `(,(erlang:system_info 'otp_release)))" \
    -s erlang halt
```

**Note**: I use [fish][2] but had to escape it like this for bash, YMMV:
```bash
lfe -noshell \
    -eval "(lfe_io:format \"~s\n\" \`(,(erlang:system_info 'otp_release)))" \
    -s erlang halt
```

I get:
```
18
```


[1]: https://github.com/lfex/ltest
[2]: http://fishshell.com

**Comment by verdammelt** [comment] 2015-07-30 01:07
>>>>> On Wed, 29 Jul 2015 17:45:14 -0700, Eric Bailey <notifications@github.com> said:

    Eric> Thanks for the feedback! Sorry you're having trouble..

Sorry I had to be the first issue of your track :(. But I think you've
given me the missing secret info!

    Eric> Do you have a rebar.config file in your /path/to/exercism/lfe
    Eric> directory? I'm not intimately familiar with the way Exercism
    Eric> works so it may not be giving it to you, but you'll need a
    Eric> rebar.config there that looks like this:

It is *not* being provided to me. I don't think that anything outside of
the exercise directories are provided by `exercism fetch`. And even
there it is doing some shenanigans to pull in the README etc. (Maybe
@kytrinyx can pop in for some details on this.)

I created that file and then ran the `rebar get-deps` and `rebar
compile` commands and they created a deps directory so I was then able
to set `ERL_LIBS` and then run the `lfe` command line to run the tests -
which fail! Yay failing tests!


    Eric> Just to make sure everything installed correctly, could you
    Eric> run the following and post the output?
    Eric> 
    Eric> lfe -noshell \ -eval "(lfe_io:format \"~s\n\"
    Eric> \`(,(erlang:system_info 'otp_release)))" \ -s erlang halt
    Eric> 
    Eric> I get:
    Eric>
    Eric> 18

I get: 17

I guess baring some way to create that `rebar.config` file in the `lfe`
directory that we'd need to update the getting started instructions.

**Comment by kytrinyx** [comment] 2015-07-30 01:09
> I don't think that anything outside of the exercise directories are provided by `exercism fetch`

The `exercism fetch` is supposed to pull in everything except files with `/example/` in the filename.

**Comment by verdammelt** [comment] 2015-07-30 01:24
It doesn't seem like files in the `xlfe` directory are being copied to the `lfe` directory of the exercise directory. I know that doesn't happy in `xlisp` (not that we have anything there we'd like to put into the user's exercise directory - but if we *could* I think it could use it to our advantage (*i.e.* installing utility libraries or scripts).

**Comment by yurrriq** [comment] 2015-07-30 01:47
I'm cooking up a different approach, using [lfetool][1] and [rebar][2], which is similar to the [Clojure track][3] and its use of [Leiningen][4] (and provided `project.clj` files).

#### Added Files
##### `./rebar.config`
```erlang
{erl_opts, [debug_info, {src_dirs, ["test"]}]}.
{lfe_first_files, []}.
{deps_dir, ["deps"]}.
{eunit_compile_opts,
 [{src_dirs, ["test"]}]}.
{deps,
 [{lfe,   ".*", {git, "git://github.com/rvirding/lfe.git", {tag, "v0.9.2"}}},
  {ltest, ".*", {git, "git://github.com/lfex/ltest.git",   {tag, "0.6.1"}}}]}.
```
##### `./src/leap.app.src`
```erlang
%% -*- erlang -*-
{application, 'leap',
 [{description, "Determining if a year is a leap year."},
  {vsn, "0.0.1"},
  {modules,
   ['leap']},
  {registered, []},
  {applications,
   [kernel, stdlib]},
  {included_applications, []},
  {env, []}]}.
```

#### Proposed Workflow
*Output truncated for brevity.*
- Ensure [lfetool][1] is installed
-  `exercism fetch lfe`
-  `cd leap`
```bash
$ ls -1R
README.md
rebar.config   # new
src            # new
test           # new

./src:
leap.app.src   # new
leap.lfe       # user-created, maybe we should stub it

./test:
leap-tests.lfe # moved to ./test
  ```
- `rebar get-deps compile` N.B. You can call both inline like that.
```
==> lfe (get-deps)
==> ltest (get-deps)
==> leap (get-deps)
==> lfe (compile)
==> ltest (compile)
==> leap (compile)
```
- Write code in `./src/leap.lfe`
- `rebar complie`
```
==> lfe (compile)
==> lutil (compile)
==> color (compile)
==> ltest (compile)
==> leap (compile)
```
- `lfetool tests unit`
```
Removing old tests ...
rm -rf ./.eunit
mkdir: created directory ./.eunit
Compiling tests ...
Successfully compiled test modules.


------------------
Running unit tests ...
------------------

======================== EUnit ========================
module 'leap-tests'
  leap-year ............................ [0.002 s] [ok]
  non-leap-year .................................. [ok]
  century ........................................ [ok]
  fourth-century ................................. [ok]
  Total module test time: 0.014 s
=======================================================
  All 4 tests passed.
```


What do y'all of that? @oubiwann?




[1]: https://github.com/lfex/ltool
[2]: https://github.com/rebar/rebar
[3]: https://github.com/exercism/xclojure
[4]: http://leiningen.org

**Comment by yurrriq** [comment] 2015-07-30 01:48
@verdammelt, I'm glad you got the failing tests to run!

**Comment by verdammelt** [comment] 2015-07-30 01:52
@yurrriq I like the idea of having everything in the exercise directory. Without the need to set `ERL_LIBS` and having it be just two commands `rebar` and `lfetool` means that I could easily script that.

I think it would be easier on other beginners (pardon me other beginners for speaking for you..)

**Comment by yurrriq** [comment] 2015-07-30 01:56
One (of many) bonus(es) of using [lfetool][1] is that we get colorized output. :tada:
![image](https://cloud.githubusercontent.com/assets/1866448/8974164/4a34fe0e-3634-11e5-9078-e646bf519562.png)

**Comment by verdammelt** [comment] 2015-07-30 01:59
Kids these days and their colored shell output... looks like angry fruit salad! ;)

**Comment by yurrriq** [comment] 2015-07-30 02:04
>  I like the idea of having everything in the exercise directory. Without the need to set `ERL_LIBS` and having it be just two commands `rebar` and `lfetool` means that I could easily script that.

@verdammelt, I've just confirmed that `ERL_LIBS` is not necessary in this new workflow. I wasn't sure.
If no one objects, I can add the config files to each exercise. The modified file tree encourages good (necessary?) habits too. :grinning:

**Comment by verdammelt** [comment] 2015-07-30 02:24
:+1: 

Encouraging (or even forcing!) good habits sounds good. Since we beginners have no idea what we are doing - we need all the help we can get!

**Comment by kytrinyx** [comment] 2015-07-30 15:22
It would be useful to have a way to get common track-level files to the user. We don't have that yet.

**Comment by oubiwann** [comment] 2015-07-31 05:11
@yurrriq Hrm, to be honest, I'd make this as simple for the learners as possible: put everything in a ``Makefile`` (one for each exercise). So, to modify your plan:

1. Ensure ``lfetool`` is installed (you can even have a check at the top of your ``Makefile`` that does this)
1. ``exercism fetch lfe``
1. ``cd leap``
1. ``make`` (have this do ``rebar get-deps compile``)
1. write code
1. ``make test`` (have this do ``rebar compile && lfetool tests unit``)

I think that will provide the cleanest user experience.

It also reflects how many of the LFE projects work: ``Makefile``s wrapping tools, etc.

(In the future, when lfetool provides as much functionality as lein, this could all be done with lfetool alone, but we're not there yet ...)

**Comment by yurrriq** [comment] 2015-07-31 05:16
@oubiwann, I like that a lot! So much less to remember and chances are users are already familiar with a `make` and `make test` flow.

**Comment by verdammelt** [comment] 2015-07-31 11:52
:+1:

**Comment by oubiwann** [comment] 2015-07-31 11:58
Great!

Here's what LFE projects have at the top of their ``Makefile``s:

```make
ifeq ($(shell which erl),)
$(error Can't find Erlang executable 'erl')
exit 1
endif
```

You can have that and then add one for lfetool:
```make
ifeq ($(shell which lfetool),)
$(error Can't find lfetool)
exit 1
endif
```

(and maybe another for ``rebar`` ... my ``make`` foo isn't strong enough to consolidate three of these into one general one)

The other bits should be fairly straightforward ...

**Comment by yurrriq** [comment] 2015-07-31 13:06
I can give it a go :sunglasses:

**Comment by yurrriq** [comment] 2015-07-31 23:49
First draft: lfex/xlfe@fdd4656b0ed5579dca6940fdaedfcfb4813bc055
#### TODO
- [ ] Automate transition
- [ ] Set up all other exercises
- [ ] Update documentation

**Comment by yurrriq** [comment] 2015-08-02 01:20
Merged in the new flow. Haven't updated the documentation yet, but the details are outlined in this thread. Here goes nothing!

**Comment by kytrinyx** [comment] 2015-08-02 15:17
Epic!

**Comment by canweriotnow** [comment] 2015-08-03 06:17
Tangentially related... I've been thinking about some of the scripts I put
in the bin dirs of the track repos (stub.sh in xscheme, etc.), and realized
how handy it would be to be able to provide some per-track scripts in some
cases (e.g., if you look at the help docs for elisp, I suggest a short bash
script for running the annoyingly long command for batch-running ert tests
from the command line).

Of course, one wouldn't want to burden the user with setting $PATH over and
over or clutter up their ~/bin/ dir.

So my latest thought was having a per-track bin dir, perhaps hidden so as
not to be confused with the exercise dirs, that could be sourced by the
exercism CLI. I'm not sure how much effort this would be on adding a
feature to the CLI, but perhaps some extensibility along the lines of 'when
called with an unknown argument, first look in the current track's
directory for a hidden directory called .bin or .support or .scripts, and
if an executable file of that name is found, run it. Else error unknown
command as usual."

Just a passing thought, but it could add extensibility to the cli as well
as a way to easily provide helper scripts/tasks via a common interface.

**Comment by yurrriq** [comment] 2015-08-03 06:43
Sounds good to me!

I think we've sort of obsoleted the need for track-level files in LFE for now, but I can definitely see the benefit. Maybe something more generic like `.exercism` so track maintainers could put whatever they want in there and the chance of colliding with some other functionality is very low. I like `.support` too. I guess my main point is to avoid specifics like `bin` or `doc`.

**Comment by verdammelt** [comment] 2015-08-03 23:56
@canweriotnow That is an interesting idea. But would not be useful to me. I run most things in Emacs, and for some of these tracks I'm running things in REPLs not command lines. It could be useful on some tracks though I imagine.

**Comment by verdammelt** [comment] 2015-08-04 00:00
@yurrriq So what do I need to do to see this new workflow? I tried blowing away the lfe exercise directory and then refetching but didn't get anything but the readme & test file in my next track.

**Comment by yurrriq** [comment] 2015-08-04 00:10
@verdammelt, It's possibly not yet merged into [x-api](https://github.com/exercism/x-api).

**Comment by yurrriq** [comment] 2015-08-04 00:15
^ confirmed.

**Comment by verdammelt** [comment] 2015-08-04 00:19
Thanks. I'll try again in N days, for a reasonably small value of N.

**Comment by verdammelt** [comment] 2015-08-16 17:55
Just wanted to pop in and let you know that the N days mentioned above is no greater than 13. Not sure how much less it was though.

I have not successfully used the new style setup unfortunately as I do not have `lfetool` installed. Looks like I need to go to https://github.com/lfex/ltool and follow those directions now? The setup page for exercism doesn't mention it - so that is an issue.

**Closed** 2015-08-16 17:56 UTC

**Comment by yurrriq** [comment] 2015-08-16 18:03
Yeah, the instructions should be pretty straightforward. Let me know if you have issues. I definitely need to update the setup page.. I'll to to do that today.

**Comment by yurrriq** [comment] 2015-08-16 18:03
I'm not sure if the new setup is live, due to the symlink/gitignore issues.. Sorry I've sort of dropped the ball on this lately.

**Comment by kytrinyx** [comment] 2015-08-16 19:25
> So my latest thought was having a per-track bin dir, perhaps hidden so as not to be confused with the exercise dirs, that could be sourced by the exercism CLI. I'm not sure how much effort this would be on adding a feature to the CLI

For a moment I thought this was already supported, but it's not. It would be really useful, though, and I think it's worth adding the feature. It wouldn't require much work on the CLI (mostly just a new command, such as `exercism deps LANGUAGE`... writing files is writing files).

The API would have to know about this, though, and have a way to return it.

**Comment by yurrriq** [comment] 2015-08-16 19:33
That would be awesome, then we could commit the empty (except .gitignore) deps dir at the LFE track level and all the symlinks would be happy. For now I was gonna add "run mkdir deps" to the getting started guide.
